// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;
import frc.robot.Constants;
import frc.robot.PowerCurve;


public class ArmSubsystem extends SubsystemBase {
   
    private WPI_TalonFX armMotorController;

    private double powerExp = 2.5;

   
    public ArmSubsystem() {
        // TODO
        // armMotorController = new PWMTalonFX(4);
        // addChild("ArmMotorController",armMotorController);
        // armMotorController.setInverted(false);
        armMotorController = new WPI_TalonFX(Constants.ArmMotorID);

        
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void drive(double motorSpeed, double speedFactor){
        armMotorController.set(PowerCurve.getPoint(motorSpeed, powerExp) * 0.5);
    }

}

