// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.PneumaticsModuleType;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.Relay;
import frc.robot.Constants;

public class FootSubsystem extends SubsystemBase {
    private DoubleSolenoid footSolenoid;    //open and closing gripper solenoid which controls valve
    private Relay alertLight;

    public FootSubsystem() {
        footSolenoid = new DoubleSolenoid(Constants.PneumaticsID, PneumaticsModuleType.CTREPCM, 4, 5);
        addChild("footSolenoid", footSolenoid);
        alertLight = new Relay(0, Relay.Direction.kForward);
    }

    @Override
    public void periodic() {
    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }

    public void retractFoot() {
        footSolenoid.set(Value.kForward);
        alertLight.set(Relay.Value.kOff);
}

    public void extendFoot() {
        footSolenoid.set(Value.kReverse);
        System.out.println("light should be on!!!!!");
        alertLight.set(Relay.Value.kOn);
    }

    public boolean isExtended() {
        return footSolenoid.get() == Value.kReverse;
    }
}